# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hyehye12
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-service-students02
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-node2-students02

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  deploymentBucket:
    name: tmd-genai1-students02
    blockPublicAccess: true
    serverSideEncryption: AES256
  environment:
    USERS_TABLE: ${self:service}-user-${sls:stage} # my-service-students02-user-dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:ap-northeast-2:654654611599:table/my-service-students02-user-dev

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


functions:
  getUser:
    handler: handler.getUser
    events:
      - httpApi:
          path: /users/{id}
          method: get

  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /users/{id}
          method: post

  updateUser:
    handler: handler.updateUser
    events:
      - httpApi:
          path: /users/{id}
          method: put

  deleteUser:
    handler: handler.deleteUser
    events:
      - httpApi:
          path: /users/{id}
          method: delete
